/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilh
 */
public class CrudCidadao extends javax.swing.JFrame {

    /**
     * Creates new form CrudCidadao
     */
    public CrudCidadao() {
        initComponents();
        cbVacinaCidadao.setModel(new javax.swing.DefaultComboBoxModel<>(new Vacina().listarVacinas()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRelatorio = new javax.swing.JLabel();
        btnCidadao = new javax.swing.JLabel();
        btnVacinas1 = new javax.swing.JLabel();
        btnFuncioanrio = new javax.swing.JLabel();
        CardPai = new javax.swing.JPanel();
        pai = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cidadao = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        panelCidadao = new javax.swing.JPanel();
        txtfDataNascimentoCidadao = new javax.swing.JFormattedTextField();
        txtfCpfCidadao = new javax.swing.JFormattedTextField();
        txtNomeCidadao = new javax.swing.JTextField();
        txtEnderecoCidadao = new javax.swing.JTextField();
        txtEmailCidadao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtfCelularCidadao = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnEditarCidadao = new javax.swing.JButton();
        btnExcluirCidadao = new javax.swing.JButton();
        btnGravarCidadao = new javax.swing.JButton();
        cbVacinaCidadao = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtfDataVacinacao = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        ComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ComboBox3 = new javax.swing.JComboBox<>();
        btnPesquisar = new javax.swing.JLabel();
        Vacinas = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        panelVacinas = new javax.swing.JPanel();
        txtNomeVacina = new javax.swing.JTextField();
        txtFornecedor = new javax.swing.JTextField();
        btnExcluirCidadao1 = new javax.swing.JButton();
        btnGravarCidadao1 = new javax.swing.JButton();
        btnEditarCidadao1 = new javax.swing.JButton();
        ComboQuantidadeDoses = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtQuantidadeVacinas = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtDataChega = new javax.swing.JFormattedTextField();
        txtHoraChega = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtValidade = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        txtImunidade = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        Relatorio = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Funcionario = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(42, 51, 122));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnRelatorio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/relatorioicon.png"))); // NOI18N
        btnRelatorio.setText("Relatorio");
        btnRelatorio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnRelatorio.setPreferredSize(new java.awt.Dimension(153, 50));
        btnRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelatorioMouseClicked(evt);
            }
        });

        btnCidadao.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        btnCidadao.setForeground(new java.awt.Color(255, 255, 255));
        btnCidadao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCidadao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        btnCidadao.setText("Cidadão ");
        btnCidadao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCidadao.setPreferredSize(new java.awt.Dimension(153, 50));
        btnCidadao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCidadaoMouseClicked(evt);
            }
        });

        btnVacinas1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnVacinas1.setForeground(new java.awt.Color(255, 255, 255));
        btnVacinas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVacinas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vaccineicon.png"))); // NOI18N
        btnVacinas1.setText("Vacinas");
        btnVacinas1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnVacinas1.setPreferredSize(new java.awt.Dimension(153, 50));
        btnVacinas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVacinas1MouseClicked(evt);
            }
        });

        btnFuncioanrio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnFuncioanrio.setForeground(new java.awt.Color(255, 255, 255));
        btnFuncioanrio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFuncioanrio.setText("Funcionario");
        btnFuncioanrio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnFuncioanrio.setPreferredSize(new java.awt.Dimension(153, 50));
        btnFuncioanrio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFuncioanrioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCidadao, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(btnVacinas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFuncioanrio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btnCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnVacinas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnFuncioanrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardPai.setBackground(new java.awt.Color(0, 0, 153));
        CardPai.setLayout(new java.awt.CardLayout());

        pai.setBackground(new java.awt.Color(47, 59, 137));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("x");
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 40));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cLogoSãojudsa.png"))); // NOI18N

        javax.swing.GroupLayout paiLayout = new javax.swing.GroupLayout(pai);
        pai.setLayout(paiLayout);
        paiLayout.setHorizontalGroup(
            paiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paiLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel6)
                .addGap(0, 259, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        paiLayout.setVerticalGroup(
            paiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paiLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(205, 205, 205))
        );

        CardPai.add(pai, "filho1");

        Cidadao.setBackground(new java.awt.Color(47, 59, 137));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("x");
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 40));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cLogoSãojudsa.png"))); // NOI18N

        panelCidadao.setBackground(new java.awt.Color(255, 252, 252));
        panelCidadao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelCidadao.setForeground(new java.awt.Color(255, 254, 254));

        try {
            txtfDataNascimentoCidadao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfDataNascimentoCidadao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfDataNascimentoCidadao.setText("");
        txtfDataNascimentoCidadao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDataNascimentoCidadaoActionPerformed(evt);
            }
        });

        try {
            txtfCpfCidadao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfCpfCidadao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfCpfCidadao.setText("");

        txtNomeCidadao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCidadaoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Nome Completo: ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Endereço:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Email:");

        try {
            txtfCelularCidadao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfCelularCidadao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtfCelularCidadao.setText("");
        txtfCelularCidadao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfCelularCidadaoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Data de Nascimento: ");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("CPF:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Celular:");

        btnEditarCidadao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Editicon.png"))); // NOI18N
        btnEditarCidadao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEditarCidadao.setBorderPainted(false);
        btnEditarCidadao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarCidadao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarCidadaoMouseClicked(evt);
            }
        });
        btnEditarCidadao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCidadaoActionPerformed(evt);
            }
        });

        btnExcluirCidadao.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnExcluirCidadao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Removeicon.png"))); // NOI18N
        btnExcluirCidadao.setActionCommand("Deletar");
        btnExcluirCidadao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnExcluirCidadao.setBorderPainted(false);
        btnExcluirCidadao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirCidadao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirCidadaoMouseClicked(evt);
            }
        });
        btnExcluirCidadao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCidadaoActionPerformed(evt);
            }
        });

        btnGravarCidadao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Addusericon.png"))); // NOI18N
        btnGravarCidadao.setActionCommand("Deletar");
        btnGravarCidadao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnGravarCidadao.setBorderPainted(false);
        btnGravarCidadao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGravarCidadao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGravarCidadao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGravarCidadaoMouseClicked(evt);
            }
        });
        btnGravarCidadao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarCidadaoActionPerformed(evt);
            }
        });

        cbVacinaCidadao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Item 2", "Item 3", "Item 4" }));
        cbVacinaCidadao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVacinaCidadaoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Vacinas");

        try {
            txtfDataVacinacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfDataVacinacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfDataVacinacao.setText("");
        txtfDataVacinacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDataVacinacaoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Data de Vacinação ");

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1 Dose", "2 Dose" }));
        ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Doses Tomadas");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Trabalha na área da Saúde:");

        ComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "SIM", "NÃO" }));

        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pesquisar1.png"))); // NOI18N
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPesquisar.setMaximumSize(new java.awt.Dimension(153, 50));
        btnPesquisar.setMinimumSize(new java.awt.Dimension(153, 50));
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCidadaoLayout = new javax.swing.GroupLayout(panelCidadao);
        panelCidadao.setLayout(panelCidadaoLayout);
        panelCidadaoLayout.setHorizontalGroup(
            panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCidadaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCidadaoLayout.createSequentialGroup()
                        .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCidadaoLayout.createSequentialGroup()
                                .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCidadaoLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel13))
                                        .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelCidadaoLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(txtEmailCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelCidadaoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbVacinaCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panelCidadaoLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNomeCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCidadaoLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfDataVacinacao, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCidadaoLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfDataNascimentoCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelCidadaoLayout.createSequentialGroup()
                                .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCidadaoLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel20))
                                    .addGroup(panelCidadaoLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addGap(30, 30, 30))
                    .addGroup(panelCidadaoLayout.createSequentialGroup()
                        .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCidadaoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfCelularCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCidadaoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEnderecoCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfCpfCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))
                    .addGroup(panelCidadaoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditarCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnGravarCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnExcluirCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))))
        );
        panelCidadaoLayout.setVerticalGroup(
            panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCidadaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNomeCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtfDataNascimentoCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtEnderecoCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(txtfCpfCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtEmailCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfCelularCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txtfDataVacinacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(cbVacinaCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(ComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluirCidadao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarCidadao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGravarCidadao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout CidadaoLayout = new javax.swing.GroupLayout(Cidadao);
        Cidadao.setLayout(CidadaoLayout);
        CidadaoLayout.setHorizontalGroup(
            CidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CidadaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCidadao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CidadaoLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(240, 240, 240))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CidadaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CidadaoLayout.setVerticalGroup(
            CidadaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CidadaoLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(panelCidadao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        CardPai.add(Cidadao, "Cidadao");

        Vacinas.setBackground(new java.awt.Color(47, 59, 137));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("x");
        jLabel8.setPreferredSize(new java.awt.Dimension(40, 40));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cLogoSãojudsa.png"))); // NOI18N

        panelVacinas.setBackground(new java.awt.Color(255, 252, 252));
        panelVacinas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelVacinas.setPreferredSize(new java.awt.Dimension(684, 255));

        txtFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFornecedorActionPerformed(evt);
            }
        });

        btnExcluirCidadao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Removeicon.png"))); // NOI18N
        btnExcluirCidadao1.setActionCommand("Deletar");
        btnExcluirCidadao1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluirCidadao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirCidadao1MouseClicked(evt);
            }
        });
        btnExcluirCidadao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCidadao1ActionPerformed(evt);
            }
        });

        btnGravarCidadao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Addusericon.png"))); // NOI18N
        btnGravarCidadao1.setActionCommand("Deletar");
        btnGravarCidadao1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGravarCidadao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGravarCidadao1MouseClicked(evt);
            }
        });

        btnEditarCidadao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Editicon.png"))); // NOI18N
        btnEditarCidadao1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarCidadao1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEditarCidadao1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarCidadao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarCidadao1MouseClicked(evt);
            }
        });

        ComboQuantidadeDoses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboQuantidadeDoses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1 Dose", "2 Doses" }));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Quantidade de Doses:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Nome da Vacina:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Nome do Fornecedor:");

        txtQuantidadeVacinas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtQuantidadeVacinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeVacinasActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Quantidade de Vacinas:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Imunidade em meses");

        try {
            txtDataChega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataChega.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataChega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataChegaActionPerformed(evt);
            }
        });

        try {
            txtHoraChega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHoraChega.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHoraChega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraChegaActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Vacina Hora ");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Vacina Data");

        try {
            txtValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtValidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValidadeActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Validade");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Id");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pesquisar1.png"))); // NOI18N
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelVacinasLayout = new javax.swing.GroupLayout(panelVacinas);
        panelVacinas.setLayout(panelVacinasLayout);
        panelVacinasLayout.setHorizontalGroup(
            panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVacinasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVacinasLayout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30))
                    .addGroup(panelVacinasLayout.createSequentialGroup()
                        .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelVacinasLayout.createSequentialGroup()
                                    .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel21))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtQuantidadeVacinas)
                                        .addComponent(ComboQuantidadeDoses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(panelVacinasLayout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNomeVacina, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelVacinasLayout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelVacinasLayout.createSequentialGroup()
                                .addComponent(btnEditarCidadao1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnGravarCidadao1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelVacinasLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnExcluirCidadao1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVacinasLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelVacinasLayout.createSequentialGroup()
                                        .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel28))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDataChega, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHoraChega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelVacinasLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtImunidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVacinasLayout.setVerticalGroup(
            panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVacinasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtImunidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtNomeVacina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtDataChega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(ComboQuantidadeDoses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtHoraChega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtQuantidadeVacinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(panelVacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarCidadao1)
                    .addComponent(btnGravarCidadao1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirCidadao1))
                .addContainerGap())
        );

        javax.swing.GroupLayout VacinasLayout = new javax.swing.GroupLayout(Vacinas);
        Vacinas.setLayout(VacinasLayout);
        VacinasLayout.setHorizontalGroup(
            VacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VacinasLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(VacinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelVacinas, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VacinasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        VacinasLayout.setVerticalGroup(
            VacinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VacinasLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(panelVacinas, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        CardPai.add(Vacinas, "Vacina");

        Relatorio.setBackground(new java.awt.Color(47, 59, 137));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("x");
        jLabel9.setPreferredSize(new java.awt.Dimension(40, 40));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Celular", "Dia da segunda vacina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout RelatorioLayout = new javax.swing.GroupLayout(Relatorio);
        Relatorio.setLayout(RelatorioLayout);
        RelatorioLayout.setHorizontalGroup(
            RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RelatorioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        RelatorioLayout.setVerticalGroup(
            RelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RelatorioLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CardPai.add(Relatorio, "Relatorio");

        Funcionario.setBackground(new java.awt.Color(47, 59, 137));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("x");
        jLabel10.setPreferredSize(new java.awt.Dimension(40, 40));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 252, 252));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Cpf:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("RG:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Telefone:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("Endereço:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administrador", "Atendete" }));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setText("Funcionario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel33))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel34)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cLogoSãojudsa.png"))); // NOI18N

        javax.swing.GroupLayout FuncionarioLayout = new javax.swing.GroupLayout(Funcionario);
        Funcionario.setLayout(FuncionarioLayout);
        FuncionarioLayout.setHorizontalGroup(
            FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(FuncionarioLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(237, 237, 237))
            .addGroup(FuncionarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FuncionarioLayout.setVerticalGroup(
            FuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FuncionarioLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(93, 93, 93)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        CardPai.add(Funcionario, "Funcionario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CardPai, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CardPai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(887, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCidadaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCidadaoMouseClicked
        CardLayout cl = (CardLayout) CardPai.getLayout();
        cl.show(CardPai, "Cidadao");
    }//GEN-LAST:event_btnCidadaoMouseClicked

    private void btnVacinas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVacinas1MouseClicked
        CardLayout cl = (CardLayout) CardPai.getLayout();
        cl.show(CardPai, "Vacina");
    }//GEN-LAST:event_btnVacinas1MouseClicked

    private void btnRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelatorioMouseClicked
        CardLayout cl = (CardLayout) CardPai.getLayout();
        cl.show(CardPai, "Relatorio");

        //Cidadao cidadao = new Cidadao();
        carregaTabela();

    }//GEN-LAST:event_btnRelatorioMouseClicked

    private void btnFuncioanrioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncioanrioMouseClicked
        CardLayout cl = (CardLayout) CardPai.getLayout();
        //cl.show(CardPai, "Funcionario");
    }//GEN-LAST:event_btnFuncioanrioMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(1);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txtfDataNascimentoCidadaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDataNascimentoCidadaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDataNascimentoCidadaoActionPerformed

    private void txtNomeCidadaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCidadaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCidadaoActionPerformed

    private void txtfCelularCidadaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfCelularCidadaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfCelularCidadaoActionPerformed

    private void btnEditarCidadaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCidadaoMouseClicked
        String nome = txtNomeCidadao.getText();
        String endereco = txtEnderecoCidadao.getText();
        String dataNascimento = txtfDataNascimentoCidadao.getText();
        String email = txtEmailCidadao.getText();
        String celular = txtfCelularCidadao.getText();
        String associado_saude = ComboBox3.getSelectedItem().toString();
        String nomeVacina = cbVacinaCidadao.getSelectedItem().toString();
        String dosesTomadas = ComboBox1.getSelectedItem().toString();
        String cpf = txtfCpfCidadao.getText();
        String dataVacinacao = txtfDataVacinacao.getText();

        if (cpf.equals("")) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar", "Informe o cpf", JOptionPane.ERROR_MESSAGE);
        } else {
            Cidadao cidadao = new Cidadao();
            cidadao.setNome(nome);
            cidadao.setEndereco(endereco);
            cidadao.setDataNascimento(dataNascimento);
            cidadao.setEmail(email);
            cidadao.setCelular(celular);
            cidadao.setAssociado_saude(associado_saude);
            cidadao.setNomeVacina(nomeVacina);
            cidadao.setDosesTomadas(dosesTomadas);
            cidadao.setDataVacinacao(dataVacinacao);
            cidadao.setCpf(cpf);

            //alterando os dados do Cidadao
            cidadao.alterar();

            //limpando os campos
            txtNomeCidadao.setText("");
            txtEnderecoCidadao.setText("");
            txtfDataNascimentoCidadao.setText("");
            txtEmailCidadao.setText("");
            txtfCelularCidadao.setText("");
            txtfCpfCidadao.setText("");
            ComboBox3.setSelectedItem("Selecione");
            cbVacinaCidadao.setSelectedItem("Selecione");
            txtfDataVacinacao.setText("");
            ComboBox1.setSelectedItem("Selecione");
            txtfDataVacinacao.setText("");
        }
    }//GEN-LAST:event_btnEditarCidadaoMouseClicked

    private void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        //arrumando layout da tabela
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(65);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(65);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(65);
        //aumenta o tamanho entre as linhas
        jTable1.setRowHeight(25);
        
        // jTable1.getColumnModel().getColumn(0).setMaxWidth(80);
        //jTable1.getColumnModel().getColumn(1).setMaxWidth(80);
        //jTable1.getColumnModel().getColumn(2).setMaxWidth(80);
        //Cidadao cidadao = new Cidadao();

        String sql = "SELECT nome, email, celular FROM Cidadao";

        ConnectionFactory factory = new ConnectionFactory();
        try ( Connection c = factory.obtemConexao()) {
            PreparedStatement ps = c.prepareStatement(sql);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),});

            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro com banco de dados");
        }
    }

    private void btnEditarCidadaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCidadaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarCidadaoActionPerformed

    private void btnExcluirCidadaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirCidadaoMouseClicked
        String cpf = txtfCpfCidadao.getText();

        Cidadao cidadao = new Cidadao();
        cidadao.setCpf(cpf);

        cidadao.excluir();
        //limpando os campos
        txtNomeCidadao.setText("");
        txtEnderecoCidadao.setText("");
        txtfDataNascimentoCidadao.setText("");
        txtEmailCidadao.setText("");
        txtfCelularCidadao.setText("");
        txtfCpfCidadao.setText("");
        ComboBox3.setSelectedItem("Selecione");
        cbVacinaCidadao.setSelectedItem("Selecione");
        txtfDataVacinacao.setText("");
        ComboBox1.setSelectedItem("Selecione");
    }

    /*public void getTxt() throws Exception{

            pegarDadosProjeto dB = new pegarDadosProjeto();
            dataAniversarioIdade dtI = new dataAniversarioIdade();

            String nome = txtNomeCidadao.getText();
            String endereco = txtEnderecoCidadao.getText();
            int idade = dtI.fazerIdade(txtfDataNascimentoCidadao.getText());
            String dataNascimento = txtfDataNascimentoCidadao.getText();
            String CPF = txtfCpfCidadao.getText();
            String email = txtEmailCidadao.getText();
            String celular = txtfCelularCidadao.getText();
            String vacinaAplicada = cbVacinaCidadao.getItemAt(WIDTH);
            String dataVacinacao = txtfDataVacinacao.getText();
            String RG = "123456789012";
            Boolean associadoSaude = true;
            int dosesAplicadas = 1;
            int idVacinaAplicada = 1;
            int idAplicadorVacina = 2;

            dB.pegarPacientes(nome, endereco, idade, dataNascimento, email, celular, vacinaAplicada, dataVacinacao, RG, CPF, associadoSaude, dosesAplicadas, idVacinaAplicada, idAplicadorVacina);

        }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudCidadao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudCidadao().setVisible(true);

            }
        });
    }//GEN-LAST:event_btnExcluirCidadaoMouseClicked

    private void btnExcluirCidadaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCidadaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirCidadaoActionPerformed

    private void btnGravarCidadaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGravarCidadaoMouseClicked
        //guardando em variaveis os dados recebidos
        String nome = txtNomeCidadao.getText();
        String endereco = txtEnderecoCidadao.getText();
        String dataNascimento = txtfDataNascimentoCidadao.getText();
        String email = txtEmailCidadao.getText();
        String celular = txtfCelularCidadao.getText();
        String cpf = txtfCpfCidadao.getText();
        String associado_saude = ComboBox3.getSelectedItem().toString();
        String nomeVacina = cbVacinaCidadao.getSelectedItem().toString();
        String dosesTomadas = ComboBox1.getSelectedItem().toString();
        String dataVacinacao = txtfDataVacinacao.getText();

        if (nome.equals("") || endereco.equals("") || dataNascimento.equals("")
                || email.equals("") || celular.equals("") || cpf.equals("") || associado_saude.equals("Selecione")
                || nomeVacina.equals("Selecione") || dosesTomadas.equals("Selecione") || dataVacinacao.equals("")) {
            JOptionPane.showMessageDialog(null, "Campo em branco", "Preencha os campos", JOptionPane.ERROR_MESSAGE);
        } else {
            //atribuindo nas variaveis da classe Cidadao
            Cidadao cidadao = new Cidadao();
            cidadao.setNome(nome);
            cidadao.setEndereco(endereco);
            cidadao.setDataNascimento(dataNascimento);
            cidadao.setEmail(email);
            cidadao.setCelular(celular);
            cidadao.setCpf(cpf);
            cidadao.setAssociado_saude(associado_saude);
            cidadao.setNomeVacina(nomeVacina);
            cidadao.setDosesTomadas(dosesTomadas);
            cidadao.setDataVacinacao(dataVacinacao);

            //inserindo no banco de dados
            cidadao.inserir();

            //limpando os dados
            txtNomeCidadao.setText("");
            txtEnderecoCidadao.setText("");
            txtfDataNascimentoCidadao.setText("");
            txtEmailCidadao.setText("");
            txtfCelularCidadao.setText("");
            txtfCpfCidadao.setText("");
            ComboBox3.setSelectedItem("Selecione");
            cbVacinaCidadao.setSelectedItem("Selecione");
            txtfDataVacinacao.setText("");
            ComboBox1.setSelectedItem("Selecione");
        }
    }//GEN-LAST:event_btnGravarCidadaoMouseClicked

    private void btnGravarCidadaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarCidadaoActionPerformed

    }//GEN-LAST:event_btnGravarCidadaoActionPerformed

    private void cbVacinaCidadaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVacinaCidadaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVacinaCidadaoActionPerformed

    private void txtfDataVacinacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDataVacinacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDataVacinacaoActionPerformed

    private void ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox1ActionPerformed

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        // TODO add your handling code here:

        String cpf = txtfCpfCidadao.getText();

        if (cpf.equals("")) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar", "Informe um CPF", JOptionPane.ERROR_MESSAGE);
        } else {

            Cidadao cidadao = new Cidadao();

            cidadao.setCpf(cpf);
            cidadao = cidadao.listar();

            txtNomeCidadao.setText(cidadao.getNome());
            txtEnderecoCidadao.setText(cidadao.getEndereco());
            txtfDataNascimentoCidadao.setText(cidadao.getDataNascimento());
            txtEmailCidadao.setText(cidadao.getEmail());
            txtfCelularCidadao.setText(cidadao.getCelular());
            txtfCpfCidadao.setText(cidadao.getCpf());
            ComboBox3.setSelectedItem(cidadao.getAssociado_saude());
            cbVacinaCidadao.setSelectedItem(cidadao.getNomeVacina());
            ComboBox1.setSelectedItem(cidadao.getDosesTomadas());
            txtfDataVacinacao.setText(cidadao.getDataVacinacao());
        }

    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void txtFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornecedorActionPerformed

    private void btnExcluirCidadao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirCidadao1MouseClicked

        int id = Integer.parseInt(txtId.getText());

        Vacina vacina = new Vacina();
        vacina.setId(id);

        vacina.excluir();

        txtId.setText("");
        txtFornecedor.setText("");
        txtNomeVacina.setText("");
        ComboQuantidadeDoses.setSelectedItem("Selecione");
        txtQuantidadeVacinas.setText("");
        txtImunidade.setText("");
        txtDataChega.setText("");
        txtHoraChega.setText("");
        txtValidade.setText("");
        
        atualizar();
    }//GEN-LAST:event_btnExcluirCidadao1MouseClicked

    private void btnExcluirCidadao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCidadao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirCidadao1ActionPerformed

    private void btnGravarCidadao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGravarCidadao1MouseClicked

        String fornecedor = txtFornecedor.getText();
        String nomeVacina = txtNomeVacina.getText();
        String quantidadeVacinas = txtQuantidadeVacinas.getText();
        String quantidadeDoses = ComboQuantidadeDoses.getSelectedItem().toString();
        String imunidade = txtImunidade.getText();
        String vacinaData = txtDataChega.getText();
        String vacinaHora = txtHoraChega.getText();
        String validade = txtValidade.getText();

        if (fornecedor.equals("") || nomeVacina.equals("") || quantidadeVacinas.equals("")
                || quantidadeDoses.equals("") || imunidade.equals("") || vacinaData.equals("") || vacinaHora.equals("Selecione")
                || validade.equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Campo em branco", "Preencha os campos", JOptionPane.ERROR_MESSAGE);
        } else {
            Vacina vacina = new Vacina();
            vacina.setFornecedor(fornecedor);
            vacina.setNomeVacina(nomeVacina);
            vacina.setQuantidadeVacinas(quantidadeVacinas);
            vacina.setQuantidadeDoses(quantidadeDoses);
            vacina.setImunidade(imunidade);
            vacina.setVacinaData(vacinaData);
            vacina.setVacinaHora(vacinaHora);
            vacina.setValidade(validade);

            vacina.inseir();

            txtId.setText("");
            txtFornecedor.setText("");
            txtNomeVacina.setText("");
            txtQuantidadeVacinas.setText("");
            ComboQuantidadeDoses.setSelectedItem("Selecione");
            txtImunidade.setText("");
            txtDataChega.setText("");
            txtHoraChega.setText("");
            txtValidade.setText("");
            
            //panelVacinas.setVisible(false);
            dispose();
            atualizar();
        }
    }//GEN-LAST:event_btnGravarCidadao1MouseClicked

    public void atualizar(){
       CrudCidadao cidadao = new CrudCidadao();
       cidadao.setVisible(true);
    }
    
    private void btnEditarCidadao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCidadao1MouseClicked

        String fornecedor = txtFornecedor.getText();
        String nomeVacina = txtNomeVacina.getText();
        String quantidadeVacinas = txtQuantidadeVacinas.getText();
        String quantidadeDoses = ComboQuantidadeDoses.getSelectedItem().toString();
        String imunidade = txtImunidade.getText();
        String vacinaData = txtDataChega.getText();
        String vacinaHora = txtHoraChega.getText();
        String validade = txtValidade.getText();
        int id = Integer.parseInt(txtId.getText());

        if (txtId.equals("")) {
            JOptionPane.showMessageDialog(null, "Erro ao alterar", "Informe o cpf", JOptionPane.ERROR_MESSAGE);
        } else {
            Vacina vacina = new Vacina();

            vacina.setFornecedor(fornecedor);
            vacina.setNomeVacina(nomeVacina);
            vacina.setQuantidadeVacinas(quantidadeVacinas);
            vacina.setQuantidadeDoses(quantidadeDoses);
            vacina.setImunidade(imunidade);
            vacina.setVacinaData(vacinaData);
            vacina.setVacinaHora(vacinaHora);
            vacina.setValidade(validade);
            vacina.setId(id);

            vacina.alterar();

            txtFornecedor.setText("");
            txtNomeVacina.setText("");
            txtQuantidadeVacinas.setText("");
            ComboQuantidadeDoses.setSelectedItem("Selecione");
            txtImunidade.setText("");
            txtDataChega.setText("");
            txtHoraChega.setText("");
            txtValidade.setText("");
            txtId.setText("");
            
            atualizar();
        }
    }//GEN-LAST:event_btnEditarCidadao1MouseClicked

    private void txtQuantidadeVacinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeVacinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeVacinasActionPerformed

    private void txtDataChegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataChegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataChegaActionPerformed

    private void txtHoraChegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraChegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraChegaActionPerformed

    private void txtValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValidadeActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        int id = Integer.parseInt(txtId.getText());

        if (txtId.equals("'")) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar", "Informe um ID", JOptionPane.ERROR_MESSAGE);
        } else {
            Vacina vacina = new Vacina();

            vacina.setId(id);
            vacina = vacina.listar();

            txtFornecedor.setText(vacina.getFornecedor());
            txtNomeVacina.setText(vacina.getNomeVacina());
            txtQuantidadeVacinas.setText(vacina.getQuantidadeVacinas());
            ComboQuantidadeDoses.setSelectedItem(vacina.getQuantidadeDoses());
            txtImunidade.setText(vacina.getImunidade());
            txtDataChega.setText(vacina.getVacinaData());
            txtHoraChega.setText(vacina.getVacinaHora());
            txtValidade.setText(vacina.getValidade());
        }
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardPai;
    private javax.swing.JPanel Cidadao;
    private javax.swing.JComboBox<String> ComboBox1;
    private javax.swing.JComboBox<String> ComboBox3;
    private javax.swing.JComboBox<String> ComboQuantidadeDoses;
    private javax.swing.JPanel Funcionario;
    private javax.swing.JPanel Relatorio;
    private javax.swing.JPanel Vacinas;
    private javax.swing.JLabel btnCidadao;
    private javax.swing.JButton btnEditarCidadao;
    private javax.swing.JButton btnEditarCidadao1;
    private javax.swing.JButton btnExcluirCidadao;
    private javax.swing.JButton btnExcluirCidadao1;
    private javax.swing.JLabel btnFuncioanrio;
    private javax.swing.JButton btnGravarCidadao;
    private javax.swing.JButton btnGravarCidadao1;
    private javax.swing.JLabel btnPesquisar;
    private javax.swing.JLabel btnRelatorio;
    private javax.swing.JLabel btnVacinas1;
    private javax.swing.JComboBox<String> cbVacinaCidadao;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel pai;
    private javax.swing.JPanel panelCidadao;
    private javax.swing.JPanel panelVacinas;
    private javax.swing.JFormattedTextField txtDataChega;
    private javax.swing.JTextField txtEmailCidadao;
    private javax.swing.JTextField txtEnderecoCidadao;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JFormattedTextField txtHoraChega;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtImunidade;
    private javax.swing.JTextField txtNomeCidadao;
    private javax.swing.JTextField txtNomeVacina;
    private javax.swing.JFormattedTextField txtQuantidadeVacinas;
    private javax.swing.JFormattedTextField txtValidade;
    private javax.swing.JFormattedTextField txtfCelularCidadao;
    private javax.swing.JFormattedTextField txtfCpfCidadao;
    private javax.swing.JFormattedTextField txtfDataNascimentoCidadao;
    private javax.swing.JFormattedTextField txtfDataVacinacao;
    // End of variables declaration//GEN-END:variables
}
